### ISSUE TITLE
Constant whine from motors

### ISSUE THREAD

**Issue by boxed** [bricklife/BoostRemote#17]
When I tried the app there was a constant whine from the robot. I'm guessing it's because "move 0 units" is being sent constantly even when not touching the screen. A cursory look a the code seems to confirm this, but I'm not great at Swift and RxSwift confuses me further :P

**Comment by bricklife** [comment]
Thank you for your feedback. I'm working on this issue.

**Comment by bricklife** [comment]
@boxed Just fixed this issue on `develop` branch. I'm also submitting a new version of the app as `1.8.4`. Thanks!

**Comment by boxed** [comment]
Awesome!
